/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_drx2_bootmanager_screenshot_ScreenShotLib */

#ifndef _Included_com_drx2_bootmanager_screenshot_ScreenShotLib
#define _Included_com_drx2_bootmanager_screenshot_ScreenShotLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_drx2_bootmanager_screenshot_ScreenShotLib
 * Method:    takeScreenShot
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_drx2_bootmanager_screenshot_ScreenShotLib_takeScreenShot
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
